#!/bin/bash
#in Carbonate

#unzip all your  fastq.gz files

gunzip -d *.gz

# Remember to activate your environment.

source activate rnaseq

# Unload system perl for compatability with entrez-direct.

module unload perl



################################
## Generate STAR Genome Index ##
################################

# Make a directory to store the genome files within your working directory.
mkdir hg19
cd hg19
# Download and unpack the genome assembly.

#Download GRCh37.primary_assembly.genome.fa.gz and gencode.v28lift37.annotation.gtf from gencode and copy into hg19 folder using command prompt "scp" 
gunzip *.gz

# Create a directory to store the index.

mkdir index

# Create the STAR genome index.
# --genomeSAindexNbases 12 was recommended by software.

STAR \
  --runThreadN 8 \
  --runMode genomeGenerate \
  --genomeDir index \
  --genomeFastaFiles GRCh37.primary_assembly.genome.fa \
  --sjdbGTFfile gencode.v28lift37.annotation.gtf \
  --genomeSAindexNbases 12
  
  ###########################
## Align Reads to Genome ##
###########################

# Create an output directory for aligned reads.

mkdir staralign

# Align the reads.
#To submit a job 
#!/bin/bash

#SBATCH -J 338.11.14.merged.aligned
#SBATCH -p general
#SBATCH -o 338.11.14.aligned_%j.txt
#SBATCH -e 338.11.14.aligned_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rrkurup@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
module unload gcc
module load gcc/4.9.2
module load star

STAR --runThreadN 8 --outFilterMultimapNmax 1 --outFilterScoreMinOverLread .66 --outFilterMatchNminOverLread .66 \
--outFilterMismatchNmax 10 --outFilterMismatchNoverLmax .3  --runMode alignReads --genomeDir /N/slate/rrkurup/hg19/index \
--clip3pAdapterSeq CCGTCCCG --outFileNamePrefix /N/slate/rrkurup/hg19/staralign/338.11.14.star. --outSAMattributes all \
--outSAMtype BAM SortedByCoordinate --readFilesIn /N/slate/rrkurup/hg19/338-11-14_S2_R1_001.fastq /N/slate/rrkurup/hg19/338-11-14_S2_R2_001.fastq



# Indexing the BAM files.

BAMS=($(find /N/slate/rrkurup/hg19/staralign -name "*\.bam"))

for BAM in ${BAMS[@]}; do
  samtools index $BAM
  done
  
 
